platform :ios, '8.0'
use_frameworks!

target 'Example' do

pod 'NoticeBoard',   :path => '..'

pod 'AXKit', '0.3.3'
pod 'AXTableKit', '0.0.3'

end



#pod install --verbose --no-repo-update      #安装命令
#pod update --verbose --no-repo-update       #更新命令
