platform :ios, '9.0'
use_frameworks!

target 'Example' do
    
    pod 'NoticeBoard',   :path => '..'
    
    pod 'AXKit', '0.3.10'
    pod 'AXTableKit', '0.0.3'
    
    pod 'MarkdownView', '1.3.0'
    pod 'Inspire', :path => "../../Inspire/"
    
end



#pod install --verbose --no-repo-update      #安装命令
#pod update --verbose --no-repo-update       #更新命令
