platform :ios, '9.0'
use_frameworks!

target 'Example' do

pod 'NoticeBoard',   :path => '..'

pod 'AXKit', '0.3.4'
pod 'AXTableKit', '0.0.3'

pod 'MarkdownView', '1.3.0'

end



#pod install --verbose --no-repo-update      #安装命令
#pod update --verbose --no-repo-update       #更新命令
